version: '3.8'

services:

  db:
    image: mysql:latest
    container_name: db_cafeteria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: cafeteria
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - humanitas-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - humanitas-network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontHumanitas
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - humanitas-network

volumes:
  db_data: {}

networks:
  humanitas-network:
    driver: bridge